### ISSUE TITLE
HP. Blogs section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#10]
Blogs section = 2.5h

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5722&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-19 at LM8f2b8i@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/4a1869ad-bb48-470b-b591-64719b0a6998)
![CleanShot 2023-09-19 at Y6JsrneM@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/64467a83-0e43-46ad-9700-7d2561231b35)
![CleanShot 2023-09-19 at chY4gsXv@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/524d7f4b-13f3-482b-b565-66a1618d35d4)
![CleanShot 2023-09-19 at GIzAQvDv@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/f4da8aec-f216-4561-bc11-f54762e601b1)
![CleanShot 2023-09-19 at XFS0ndmm@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/4180280d-f8ea-4d6e-9809-1465e7f02f64)
![CleanShot 2023-09-19 at E0VbY7TI@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/2ecc5a7d-a95a-4e7e-bbca-3d3267566cf0)
![CleanShot 2023-09-19 at uR9rFtSs@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/770bbd3e-33fa-4409-bfd3-aca990000ac6)

**Comment by poltanka** [comment]
1) Зачем flex + родителя ограничь шириной ,а не содержимое заголовка 
![CleanShot 2023-11-16 at vw6etwWM](https://github.com/poltavchenko/happy-coaching/assets/36765674/e1b45cc7-533c-496c-a0ce-89aea688d098)
2) Зачем relative 
![CleanShot 2023-11-16 at FmzK2uf4](https://github.com/poltavchenko/happy-coaching/assets/36765674/44354cf5-d393-4002-982e-db3326800c38)
3) Предусмотри отступы от каждого элемента и возможость добавления указателя ссылки 
![CleanShot 2023-11-16 at QlULHK5j](https://github.com/poltavchenko/happy-coaching/assets/36765674/c706451e-10ba-4c7d-bd99-259c4a8969ea)
4) Возможно стоит ограничить троеточием текст и максимальную кол-во строк вывода дать 
![CleanShot 2023-11-16 at 19BB1x1L](https://github.com/poltavchenko/happy-coaching/assets/36765674/fe0dec52-096f-4dae-b9f0-a7a9c0acdefe)
5) Если нет кнопки 
![CleanShot 2023-11-16 at 3slHOEyq](https://github.com/poltavchenko/happy-coaching/assets/36765674/2dd4045d-9416-4e87-b8ad-f8e147d1bbfb)
