### ISSUE TITLE
HP. Free Guide section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#11]
Free Guide section = 3h
Real duration = 1h.

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=529-5640&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-19 at m3pkFyct@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/78100dbd-83cc-43d5-a253-8b29433a9620)
![CleanShot 2023-09-19 at n3JVlbnQ@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/1b76b879-cd1f-4366-8c48-0a3fda79be95)
![CleanShot 2023-09-19 at exEpfBX2@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/31b42334-62f3-4ceb-9cc7-bca895e249e1)
![CleanShot 2023-09-19 at TEV5LGqY@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/0232bb27-da7f-4aa6-9aae-9f0ece4b18f8)
![CleanShot 2023-09-19 at PKoczB3C@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/c7224f9e-a532-46a3-9c94-cedc2cd02067)
![CleanShot 2023-09-19 at wmq4o0aL@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/9ce023e4-2cc3-47e3-8f8d-03120ab59747)
![CleanShot 2023-09-19 at AMuCWmMW@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/7cd77e6d-b121-4bf4-9c39-179f63dd9763)
![CleanShot 2023-09-19 at JlZwo6XY@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/6810f535-8e68-4d3c-8720-df2ab6e2a940)

**Comment by poltanka** [comment]
1) Ограничь 
![CleanShot 2023-11-16 at RaGrXAib](https://github.com/poltavchenko/happy-coaching/assets/36765674/606f5f02-d044-4210-8c15-855a1fd2d6fb)

2) Добавь возможность менять местами картинку и текст, лучше флексами 
![CleanShot 2023-11-16 at Jex9v1UA@2x](https://github.com/poltavchenko/happy-coaching/assets/36765674/7f3570db-1477-4631-a605-5dadb9ff2712)
3) А это чего не сделал 
![CleanShot 2023-11-16 at ASo24lYv](https://github.com/poltavchenko/happy-coaching/assets/36765674/3cb0059e-88fb-4f3b-b220-a55f40f8eea9)
