### ISSUE TITLE
HP. CTA section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#12]
CTA section = 2h
Real duration = 40min
Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5874&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-19 at F6nHYWRX@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/ea6fff1c-87eb-4075-bf3f-97a0fa388094)
![CleanShot 2023-09-19 at ehJ1eYws@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/4d10a354-61eb-493a-95d3-4b084d089b29)
![CleanShot 2023-09-19 at BrtmAEvr@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/c6d08061-6a36-42a6-94ac-71fae7d51cf1)
![CleanShot 2023-09-19 at sNLUTxJS@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/889bb858-8e66-40cf-bd84-6603439e1f11)
![CleanShot 2023-09-19 at WmemIgPc@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/fa8d3842-4031-4fba-97a0-1575be1b94cf)
![CleanShot 2023-09-19 at tdIPkUhu@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/4d5309d1-f112-44ff-8fd5-8f9f491503fd)
![CleanShot 2023-09-19 at WWqZoS0G@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/8f8628d8-e276-4240-80f9-aaad0638d2ba)

**Comment by poltavchenko** [comment]
![CleanShot 2023-09-19 at s135cnnP@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/8ffc9dfc-fc49-4d0d-86e4-7aaff34edfff)

**Comment by poltanka** [comment]
1) 768-1024 зменьш відстань , бо великий контраст в зрівнянні з іншими секціями 
![CleanShot 2023-11-17 at mgAM2iRL](https://github.com/poltavchenko/happy-coaching/assets/36765674/5a27f793-54b0-45b7-b02d-ba7125177fae)

![CleanShot 2023-11-17 at Dyd2506f](https://github.com/poltavchenko/happy-coaching/assets/36765674/28037b8d-1ee6-4c26-ae5f-2300fa873a23)
2) Малюнок перший по коду на мобілах, + можна прибрати відстань бокову 
![CleanShot 2023-11-17 at jQmbFhUC](https://github.com/poltavchenko/happy-coaching/assets/36765674/3cd91157-88a1-4d2a-a159-4727f6c7c305)
3) Last-child 
![CleanShot 2023-11-17 at Q9XgmxlH](https://github.com/poltavchenko/happy-coaching/assets/36765674/174a01ba-a5d8-4507-96d6-79d4bb8798ad)
