### ISSUE TITLE
HP. Subscribe section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#13]
Subscribe section = 2h
Real duration = 40min.

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=514-5830&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-19 at 1S6J4UlF@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/5c07a4e7-025e-4075-838b-c9b141c65a64)
![CleanShot 2023-09-19 at R08vrhx0@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/260da74e-0549-42a9-a28c-62a616409f98)
![CleanShot 2023-09-19 at XMNbo3MZ@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/d4ba1ef3-236e-41dc-8976-e9a7b05c45b8)
![CleanShot 2023-09-19 at 7HcZPH1i@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/b293d53e-a189-44ef-a1fb-a06d49871ff6)
![CleanShot 2023-09-19 at bAvZiHNl@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/ccb9a056-00c8-4025-a8ed-214bee02ebf1)
![CleanShot 2023-09-19 at d3Zm8Awr@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/de5b5fe3-12a1-4d98-8e5d-c9adbbbe7c90)

**Comment by poltanka** [comment]
1) last child 
![CleanShot 2023-11-16 at 2ttnuTVt](https://github.com/poltavchenko/happy-coaching/assets/36765674/360174a6-7362-4bc9-a543-979248ecab0d)
