### ISSUE TITLE
Services page.  Hero section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#14]
Services page.  Hero section = 1h
Real duration = 1h.

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5289&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-09-23 at EDuar0MV](https://github.com/poltavchenko/happy-coaching/assets/8300008/cfdd08c2-fa8f-4ef7-9589-e550f4490cfa)
![CleanShot 2023-09-23 at l5D63eOG](https://github.com/poltavchenko/happy-coaching/assets/8300008/bb4048ba-d2b3-4569-8cdb-72c7cfd2ca37)
![CleanShot 2023-09-23 at Z7Q3tNpA](https://github.com/poltavchenko/happy-coaching/assets/8300008/5465d710-2e79-4cf9-9583-25c17799f503)
![CleanShot 2023-09-23 at rUk2mZZf](https://github.com/poltavchenko/happy-coaching/assets/8300008/183e4426-36eb-4271-858f-05579e009e65)
![CleanShot 2023-09-23 at lpsi4Buo](https://github.com/poltavchenko/happy-coaching/assets/8300008/5807d573-ff16-4e71-a631-c8d012dec360)
![CleanShot 2023-09-23 at NgtzAdJw](https://github.com/poltavchenko/happy-coaching/assets/8300008/18de498b-26df-4553-a729-695e7ff12ec7)
![CleanShot 2023-09-23 at bMUoUIY0](https://github.com/poltavchenko/happy-coaching/assets/8300008/afafe8ab-ceb4-469d-b266-c4162f8c4583)
![CleanShot 2023-09-23 at a6A9miE8](https://github.com/poltavchenko/happy-coaching/assets/8300008/385fa6f9-657e-4960-861f-bbb8ca60ca18)

Safari
![CleanShot 2023-09-23 at OmhDY6lA](https://github.com/poltavchenko/happy-coaching/assets/8300008/8ddbdd62-7448-4d55-8d1d-bba7bf981054)
![CleanShot 2023-09-23 at lPu724vW](https://github.com/poltavchenko/happy-coaching/assets/8300008/17b84c9e-7553-474f-bd08-c06954271939)
![CleanShot 2023-09-23 at cKrPAxpN](https://github.com/poltavchenko/happy-coaching/assets/8300008/3f0a889c-6e1e-4c41-8aa5-dc28a22aaef1)
![CleanShot 2023-09-23 at CeI46iWi](https://github.com/poltavchenko/happy-coaching/assets/8300008/ab257ff3-ff84-48b6-b26c-7f2b02089a73)
![CleanShot 2023-09-23 at rpd6fCf5](https://github.com/poltavchenko/happy-coaching/assets/8300008/7c3a0088-2927-4c22-b802-b5bf565cb544)
![CleanShot 2023-09-23 at I0KuL8Ux](https://github.com/poltavchenko/happy-coaching/assets/8300008/36713d0f-9656-4fdc-8049-7417f7d9b60d)
![CleanShot 2023-09-23 at FLVSkD5V](https://github.com/poltavchenko/happy-coaching/assets/8300008/9e537637-9345-4a6c-96e3-9002b729c5db)
![CleanShot 2023-09-23 at skhsFFaL](https://github.com/poltavchenko/happy-coaching/assets/8300008/58e75e54-06d0-4e16-9666-bc0cf9400c6d)
![CleanShot 2023-09-23 at yd4rzdLk](https://github.com/poltavchenko/happy-coaching/assets/8300008/8fc0de93-2c46-4e44-be03-570d2f8c7074)
![CleanShot 2023-09-23 at RBLvc21i](https://github.com/poltavchenko/happy-coaching/assets/8300008/69a890b9-d53a-4378-9d57-2e1a40665c58)
![CleanShot 2023-09-23 at klaPCxTE](https://github.com/poltavchenko/happy-coaching/assets/8300008/6549da36-07f5-40e5-b99c-6d8800b9b3e1)
![CleanShot 2023-09-23 at rQ6dfAPf](https://github.com/poltavchenko/happy-coaching/assets/8300008/4926bccf-25c1-4bb2-8ff1-103602c3a5b2)
![CleanShot 2023-09-23 at eglKGtaZ](https://github.com/poltavchenko/happy-coaching/assets/8300008/2c3f9b52-6a0d-4556-8f0c-b6af21229ae7)

iOS + iPadOS
![CleanShot 2023-09-23 at of9A1krF@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/902af840-bee8-4be7-98d4-635ad2628173)
![CleanShot 2023-09-23 at uw0ariyp@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/17693cfb-a8f1-486f-8c7a-bbea350c9914)
![CleanShot 2023-09-23 at kPfXLJH0@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/980dec34-33fa-41ee-b38f-10b3763a9280)

Accessibilities
![CleanShot 2023-09-23 at 4qc42eOq](https://github.com/poltavchenko/happy-coaching/assets/8300008/c8e492db-b1e1-4097-b194-44407310c8ad)

**Comment by poltanka** [comment]
1) Навіщо на мобілах ml-auto
![CleanShot 2023-11-20 at VB6uDILu](https://github.com/poltavchenko/happy-coaching/assets/36765674/dde9bb68-5f3a-4292-96c0-b528742441d9)
2) Ці класи перевірь необхідність 
![CleanShot 2023-11-20 at p34EgJc1](https://github.com/poltavchenko/happy-coaching/assets/36765674/6b7152c8-bb1f-4ffa-926a-84cd3b6409b6)
