### ISSUE TITLE
Services page. Services section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#15]
Services page. Services section = 3h
Real duration = 1h.
Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=529-5641&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-09-23 at 1H5Zyk6i](https://github.com/poltavchenko/happy-coaching/assets/8300008/3fe18119-ac3f-4613-a32e-e4febe9e55f8)
![CleanShot 2023-09-23 at qeHHp5ur](https://github.com/poltavchenko/happy-coaching/assets/8300008/fe63d85b-d66e-4fd9-b944-5e32331ec8c4)
![CleanShot 2023-09-23 at 3FRnFNDF](https://github.com/poltavchenko/happy-coaching/assets/8300008/e9da8033-601b-4269-90ea-cbc1e4ad70a1)
![CleanShot 2023-09-23 at Pe0C6j8l](https://github.com/poltavchenko/happy-coaching/assets/8300008/1c12219c-45a7-4327-801f-d17e97a8cbc6)
![CleanShot 2023-09-23 at VOmmzqbZ](https://github.com/poltavchenko/happy-coaching/assets/8300008/8180375c-01bd-47ef-8809-8c4985f8be3c)
![CleanShot 2023-09-23 at JthBRaQV](https://github.com/poltavchenko/happy-coaching/assets/8300008/edd86c8c-0699-410d-8cc2-256f48ade8e0)
![CleanShot 2023-09-23 at gLObHFPr](https://github.com/poltavchenko/happy-coaching/assets/8300008/03afec00-639d-4534-a604-e4657be26d08)
![CleanShot 2023-09-23 at bvdattKn](https://github.com/poltavchenko/happy-coaching/assets/8300008/55297185-800f-449c-b68d-6fdb6641ce2e)

Safari
![CleanShot 2023-09-23 at bTncv323](https://github.com/poltavchenko/happy-coaching/assets/8300008/998e422f-2f6e-42a0-923e-1f5e8af88484)
![CleanShot 2023-09-23 at YrAYCpp8](https://github.com/poltavchenko/happy-coaching/assets/8300008/90c11a8a-79ed-43a1-b4b0-d493acf5a3d0)
![CleanShot 2023-09-23 at 6k4m6t1p](https://github.com/poltavchenko/happy-coaching/assets/8300008/81db6ea9-8884-4974-9c79-7d4fc6aea90d)
![CleanShot 2023-09-23 at I5GZ4K8i](https://github.com/poltavchenko/happy-coaching/assets/8300008/1ab54cd9-5ca3-4478-b5be-9949654201c5)
![CleanShot 2023-09-23 at o1LAvxk4](https://github.com/poltavchenko/happy-coaching/assets/8300008/71a86999-08f8-458e-942e-614533bbc729)
![CleanShot 2023-09-23 at VunlcLLd](https://github.com/poltavchenko/happy-coaching/assets/8300008/76449db8-5281-4622-b92d-336c729f8c2b)
![CleanShot 2023-09-23 at EDIpUx11](https://github.com/poltavchenko/happy-coaching/assets/8300008/d1619f9d-9071-44d7-a1c8-aed13f36672f)
![CleanShot 2023-09-23 at DdxE2Eef](https://github.com/poltavchenko/happy-coaching/assets/8300008/077d39e5-d8e2-4605-8d33-788f8589d2f1)
![CleanShot 2023-09-23 at ZfJsUUsk](https://github.com/poltavchenko/happy-coaching/assets/8300008/082a00a0-9230-461d-9484-d8722e2eabb0)
![CleanShot 2023-09-23 at 1k1MCT7l](https://github.com/poltavchenko/happy-coaching/assets/8300008/804ca31b-91b0-4cc9-be8c-59c7f4987fd2)

iOS + iPadOS
![CleanShot 2023-09-23 at w1SbJnEv@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/ed803eed-f769-4d80-93ea-ed5f7c57cce1)
![CleanShot 2023-09-23 at pWWVoRC7@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/c0fa775e-3865-44d8-abd6-77a794be2530)
![CleanShot 2023-09-23 at NsPGYQUp@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/300b283a-85bc-415f-984a-354c082077f4)

Accessibilities
![CleanShot 2023-09-23 at hXB89W3d](https://github.com/poltavchenko/happy-coaching/assets/8300008/12a99759-441a-4490-8bda-19d74bcb1923)

**Comment by poltanka** [comment]
1) last child 
![CleanShot 2023-11-20 at Qyn7Mncz](https://github.com/poltavchenko/happy-coaching/assets/36765674/6bc92641-6983-4cae-a368-d936a2dce7df)
2) весь блок це посилання , посилання на онлайн-курси доступні і тд 
![CleanShot 2023-11-20 at 8dxsGJj7](https://github.com/poltavchenko/happy-coaching/assets/36765674/c1fe25c4-1a29-4f3e-bded-219f85919a7e)
3) завеликі отступи зверху і низу 
![CleanShot 2023-11-20 at 7lD2c5bK](https://github.com/poltavchenko/happy-coaching/assets/36765674/e2f70f27-81ec-48a8-ab53-7624df0b42f0)
