### ISSUE TITLE
Services page. Features v1 section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#16]
Services page. Features v1 section = 3h
Real duration = 40min

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5238&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-09-23 at 5xKnX6Rl](https://github.com/poltavchenko/happy-coaching/assets/8300008/14970def-4f7b-4067-88ac-a3d791cee44f)
![CleanShot 2023-09-23 at yNT0lWxE](https://github.com/poltavchenko/happy-coaching/assets/8300008/c00d39f2-7c30-49a0-95d8-3b7f5d80b2a7)
![CleanShot 2023-09-23 at dsaafYku](https://github.com/poltavchenko/happy-coaching/assets/8300008/0a71b739-099a-4e8b-89ed-eadc1b34ead5)
![CleanShot 2023-09-23 at vZR8QJ0A](https://github.com/poltavchenko/happy-coaching/assets/8300008/a051a15a-8f50-489b-bc58-40dfa1a00e54)
![CleanShot 2023-09-23 at HnkiZ8Nt](https://github.com/poltavchenko/happy-coaching/assets/8300008/af043537-a8c3-42b5-bd82-38c7d727f630)
![CleanShot 2023-09-23 at sQWoFvkc](https://github.com/poltavchenko/happy-coaching/assets/8300008/ead83775-cf52-4458-ac16-c654a4a8b110)
![CleanShot 2023-09-23 at 8ann6l1v](https://github.com/poltavchenko/happy-coaching/assets/8300008/38011083-ee0e-4a0a-886c-f8fb9e52d425)
![CleanShot 2023-09-23 at Gyxz4Y6j](https://github.com/poltavchenko/happy-coaching/assets/8300008/7df02aef-bab9-4447-a5c3-8eab7939470f)

Safari
![CleanShot 2023-09-23 at uSow5GLY](https://github.com/poltavchenko/happy-coaching/assets/8300008/2c0fcacf-dbc8-4e8f-8c69-ec1303e56c94)
![CleanShot 2023-09-23 at LH7YaaBA](https://github.com/poltavchenko/happy-coaching/assets/8300008/bfe0dfb0-0c35-49f9-912e-4524eb5d6159)
![CleanShot 2023-09-23 at BOH1j1ul](https://github.com/poltavchenko/happy-coaching/assets/8300008/6cafbd27-965a-4f82-b769-9ee27e91a01e)
![CleanShot 2023-09-23 at jKWD8G0W](https://github.com/poltavchenko/happy-coaching/assets/8300008/5bb6aab8-b2fa-4922-a61b-e8b1df106010)
![CleanShot 2023-09-23 at 3W7xvIbP](https://github.com/poltavchenko/happy-coaching/assets/8300008/423981d3-efab-4bc2-9583-57688a85a3c5)
![CleanShot 2023-09-23 at 6lRhu7Dp](https://github.com/poltavchenko/happy-coaching/assets/8300008/c338e4a6-6d0d-42e8-8276-b484f0559f11)
![CleanShot 2023-09-23 at oSu3wRrv](https://github.com/poltavchenko/happy-coaching/assets/8300008/1db4c93a-db5e-4e3a-91c8-25d083c9479c)
![CleanShot 2023-09-23 at AtirC2IP](https://github.com/poltavchenko/happy-coaching/assets/8300008/c3e07556-c8f4-4d6b-890b-5623dacdf6c5)
![CleanShot 2023-09-23 at ZhbIRahv](https://github.com/poltavchenko/happy-coaching/assets/8300008/b2d0fe12-cf6d-4c1b-b531-a2546cbaa995)
![CleanShot 2023-09-23 at phVq9c4j](https://github.com/poltavchenko/happy-coaching/assets/8300008/ea5e6473-a751-4e61-9d05-fe7f7cc0828e)
![CleanShot 2023-09-23 at Nq3Lfopr](https://github.com/poltavchenko/happy-coaching/assets/8300008/3649d851-a972-40b8-b1f2-15343e3c2710)
![CleanShot 2023-09-23 at I47WLR23](https://github.com/poltavchenko/happy-coaching/assets/8300008/db3a7c5c-286f-4838-ad67-9734c155f9e2)
![CleanShot 2023-09-23 at FBp9dmfs](https://github.com/poltavchenko/happy-coaching/assets/8300008/fac2ba73-76e3-498d-bf23-b3c2b0267a43)


iOS + iPadOS
![CleanShot 2023-09-23 at mD68gOYk@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/a7c3742a-74c9-412e-957d-929e434a4162)
![CleanShot 2023-09-23 at GziWGtmp@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/2d2884e6-dbf4-4cb2-a55a-bfe8e8f65555)
![CleanShot 2023-09-23 at sfyh7fit@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/8d72e2e2-922a-4025-8794-1c9caa77ae9a)

Accessibilities
![CleanShot 2023-09-23 at k3vN8rgw](https://github.com/poltavchenko/happy-coaching/assets/8300008/723bb089-29c9-4f6c-91e4-6979be12a5ff)

**Comment by poltanka** [comment]
1) Last child 
![CleanShot 2023-11-20 at mL4F2F0S](https://github.com/poltavchenko/happy-coaching/assets/36765674/f72eb4b7-e7d2-44dc-b669-70bdcba530d1)
2) не по центру 
![CleanShot 2023-11-20 at 4Yj9MjF9](https://github.com/poltavchenko/happy-coaching/assets/36765674/a7b8d00a-c01e-40d2-867a-45c4cb9c423a)
3) зроби універсальну структуру 
![CleanShot 2023-11-20 at CoIm5Xy4](https://github.com/poltavchenko/happy-coaching/assets/36765674/3c5ee939-18e5-48c7-88dd-fea58c684d16)
