### ISSUE TITLE
Services page. FAQ section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#17]
Services page. FAQ section = 3h

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5193&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-11-07 at 2pSf7Gjv](https://github.com/poltavchenko/happy-coaching/assets/8300008/f910449e-df96-4aa0-a37c-7c257e86b8c5)
![CleanShot 2023-11-07 at a8cRXFLt](https://github.com/poltavchenko/happy-coaching/assets/8300008/f558a6f1-9bea-4468-ada5-894bbab3b1c3)
![CleanShot 2023-11-07 at kzc6VbbK](https://github.com/poltavchenko/happy-coaching/assets/8300008/789218f2-a1b1-4012-9415-f8b5c30f884c)
![CleanShot 2023-11-07 at 9ihnC0A2](https://github.com/poltavchenko/happy-coaching/assets/8300008/2944b3e0-b6b5-465d-9ec3-ec7947358e15)
![CleanShot 2023-11-07 at z2dgNudH](https://github.com/poltavchenko/happy-coaching/assets/8300008/582026d8-cb50-4358-9091-5d184f538c71)
![CleanShot 2023-11-07 at Tutge4UG](https://github.com/poltavchenko/happy-coaching/assets/8300008/aa31a84a-1feb-495f-a805-3bbeae5ee233)
![CleanShot 2023-11-07 at 1W0jxiWS](https://github.com/poltavchenko/happy-coaching/assets/8300008/744ba79b-bd3e-46d3-904b-d4ec0dad10ed)

Safari
![CleanShot 2023-11-07 at 39KC4YXx@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/3cd576dd-c8bc-492c-809a-e2f681eb4a36)
![CleanShot 2023-11-07 at uHHiYs0C@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/069f25d0-35bd-4916-afd5-087efc5b936b)
![CleanShot 2023-11-07 at aZ6H8pZ6@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/7d8764cc-66b4-417f-a085-d874b2651bb7)
![CleanShot 2023-11-07 at Fq92jj8M@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/b002e553-c3a7-4d1f-9738-2329a0ff6add)
![CleanShot 2023-11-07 at DgosNhzV@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/5e84dd55-95dd-446b-a0de-ddc88ef1ad14)

Accessibilities
![CleanShot 2023-11-07 at b1fwmEUF](https://github.com/poltavchenko/happy-coaching/assets/8300008/e7765972-7bc8-4a53-864e-6c5d79e2de2b)

**Comment by poltanka** [comment]
1) Обмеж ширину , вважаю що ці блоки універсальні мають бути 
![CleanShot 2023-11-20 at 2zz1bgsv](https://github.com/poltavchenko/happy-coaching/assets/36765674/46aa6b91-4dc8-4380-8d16-6d15917932a1)
![CleanShot 2023-11-20 at xzuK8yOU](https://github.com/poltavchenko/happy-coaching/assets/36765674/e1c823d1-634b-4f95-a9df-c5dd8b6a4c00)
2) Відступ має бути на  батьківському елементі, нащо всередені +last -child
![CleanShot 2023-11-20 at MfYqV8OX](https://github.com/poltavchenko/happy-coaching/assets/36765674/c62ddfd9-bd24-471c-9c9d-376e7e755bea)
![CleanShot 2023-11-20 at 37mfnP86](https://github.com/poltavchenko/happy-coaching/assets/36765674/f9d28c15-e112-405f-ad57-b15d8c2c4e6d)
3) last-child 
![CleanShot 2023-11-20 at n41HKut9](https://github.com/poltavchenko/happy-coaching/assets/36765674/1dc9723e-9c67-4bfb-9ab8-60e324d89c14)


4) Розмір текста, більший за розмір заголовка, не гарно виходить
![CleanShot 2023-11-20 at veJmZNtx](https://github.com/poltavchenko/happy-coaching/assets/36765674/43c3150a-8943-49ab-9d35-8e181d675004)
