### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#5]
Header = 4h.
Real duration = 1.5h

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=514-5730&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-22 at mtJYt9ME](https://github.com/poltavchenko/happy-coaching/assets/8300008/2b163663-9b5f-4a7e-b2d7-0ea173bfcf1a)
![CleanShot 2023-09-22 at BObL6thn](https://github.com/poltavchenko/happy-coaching/assets/8300008/3d9c85df-5c32-4f64-a232-d93a85dfda55)
![CleanShot 2023-09-22 at Rq8CXXOw](https://github.com/poltavchenko/happy-coaching/assets/8300008/41277a4d-d8e1-4bf9-8797-b767685704bc)
![CleanShot 2023-09-22 at iu6PqosW](https://github.com/poltavchenko/happy-coaching/assets/8300008/443dd0f3-30ba-41c7-bbbb-ddf8663ab1bf)
![CleanShot 2023-09-22 at 98wZytyV](https://github.com/poltavchenko/happy-coaching/assets/8300008/4b16c534-8962-4d5a-98b5-d91e13002664)
![CleanShot 2023-09-22 at So9O5yyE](https://github.com/poltavchenko/happy-coaching/assets/8300008/0f737cd7-427c-48e8-8d71-6c2a1319d111)

**Comment by poltavchenko** [comment]
![CleanShot 2023-09-22 at seIkMiA8@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/6e9fe1d5-db2e-4a2e-92d0-68d928e732d6)
![CleanShot 2023-09-22 at Zyr9k4Eq@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/0ab0ba35-43d1-41b3-a2b2-f9e08ce7ebfd)
![CleanShot 2023-09-22 at rcFmt9Qq@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/e72e96d5-f71d-44e4-93b3-b200ac5dd5dd)
![CleanShot 2023-09-22 at h40TA9iO@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/939c1888-b60d-4b6f-a8ec-a5aa244451e6)

**Comment by poltanka** [comment]
1) отступа нет 

![Image](https://github.com/poltavchenko/happy-coaching/assets/36765674/b80afe0f-f6eb-4b23-9bda-70d5017ded27)
2) 
![CleanShot 2023-11-16 at YNDIRdhc](https://github.com/poltavchenko/happy-coaching/assets/36765674/c29ceacb-b1de-48c1-a247-0819477628da)
3) Можно обойтись без стилей 

![Image](https://github.com/poltavchenko/happy-coaching/assets/36765674/35396835-e0d1-4fbe-bfc3-de6835e7ede5)
