### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#6]
Footer = 3h
Real duration = 40min

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=514-5830&mode=dev

**Comment by poltavchenko** [comment]
Done
![CleanShot 2023-09-22 at s8yl0QGv](https://github.com/poltavchenko/happy-coaching/assets/8300008/c4318f95-478b-4487-8e92-a844b1b136f4)
![CleanShot 2023-09-22 at Lvnb1N7r](https://github.com/poltavchenko/happy-coaching/assets/8300008/e600323d-8c11-4e66-8ebf-78af5c154867)
![CleanShot 2023-09-22 at JfWdddnK](https://github.com/poltavchenko/happy-coaching/assets/8300008/cfce15b0-6086-4c58-a3b9-9a475138c7e0)
![CleanShot 2023-09-22 at pcabCGfB](https://github.com/poltavchenko/happy-coaching/assets/8300008/1eae66ce-7377-461f-852f-2243b9bc11f3)
![CleanShot 2023-09-22 at ADomlCa3](https://github.com/poltavchenko/happy-coaching/assets/8300008/8d379502-fb89-4393-8077-2dd802584d47)
![CleanShot 2023-09-22 at 6NJwTYuP](https://github.com/poltavchenko/happy-coaching/assets/8300008/8145b140-e0d7-4458-9c4b-97fd33616919)
![CleanShot 2023-09-22 at kQbLNXFX](https://github.com/poltavchenko/happy-coaching/assets/8300008/13fb10c0-c2d5-4e1f-80a1-bf90bc5f5543)
![CleanShot 2023-09-22 at Mm32c0ph](https://github.com/poltavchenko/happy-coaching/assets/8300008/bebe19fa-495b-4cc1-a3f9-40baffe86a0c)

**Comment by poltanka** [comment]
1) Что дает flex /shrink-0
![CleanShot 2023-11-16 at 5gn6dzub](https://github.com/poltavchenko/happy-coaching/assets/36765674/4ae47feb-9ebe-41b2-a7b0-6274b90f5805)
2) можно обойтись без классов ? а использовать tw
![CleanShot 2023-11-16 at WYBju5nG](https://github.com/poltavchenko/happy-coaching/assets/36765674/e409da59-e5b9-4a07-b457-4ac8d484b07e)
![Uploading CleanShot 2023-11-16 at 6OfupHMs.jpg…]()
