### ISSUE TITLE
HP. Hero section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#7]
Hero section = 4h

Real duration = 2.5h
QA duration = 20min

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5761&mode=dev

**Comment by poltavchenko** [comment]
Done
![IMG_C46D98EA11B9-1](https://github.com/poltavchenko/happy-coaching/assets/8300008/75dfda7c-8651-4d6b-9a90-02cdc5243b3e)
![CleanShot 2023-09-07 at EBSsGpbm@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/628c0bd4-ff18-4e1b-8ff3-c3bd6af2bd3c)
![CleanShot 2023-09-07 at OtkoblyU@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/dab067ad-a14a-47d0-824f-008b6c7bdb47)
![CleanShot 2023-09-07 at CDCJc4GA@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/ccc5e1f2-2235-4636-969d-cafed8eaaf24)
![CleanShot 2023-09-07 at 1Ov9uDtP@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/99a3465f-9101-4984-8bc5-203fa0f8a51d)
![CleanShot 2023-09-07 at NELvxrMg@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/59d058e5-6745-4e63-a710-5fab1b086bbc)
![CleanShot 2023-09-07 at DfiYo5rl@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/2ca3af69-9e21-4a64-ae58-998e8ccb52ac)
![CleanShot 2023-09-07 at rJUyIHBt@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/cf9a1e76-0368-4be4-b134-e4b69709a9c3)
![CleanShot 2023-09-07 at L1PZ0wNB@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/8c08513f-2633-401f-affc-8c62a1d03979)
![CleanShot 2023-09-07 at ISb5ac31@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/56d905fd-27c0-4f6b-83d1-c5ab967d62dd)

**Comment by poltavchenko** [comment]
Done

Accessibilities
![CleanShot 2023-09-07 at TReSX1r3@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/3a5b2184-ffc0-4bd8-b120-9879efb0681c)

**Comment by poltanka** [comment]
1) Looks bad link 
![CleanShot 2023-11-09 at a7kN1HqC@2x](https://github.com/poltavchenko/happy-coaching/assets/36765674/ec87d5b4-7f45-4ba2-91df-5f556b87c0f3)
2) block with margin, not paragraph 
![CleanShot 2023-11-09 at 5gqmx2Ys@2x](https://github.com/poltavchenko/happy-coaching/assets/36765674/d9a20b41-b5b7-46c9-a931-149a357ad34c)
3) Color not like as design 
![CleanShot 2023-11-09 at e94DEaVu@2x](https://github.com/poltavchenko/happy-coaching/assets/36765674/0660cd2f-49b2-4349-8177-a296fd4f59fe)
4) Indent from image , looks bad 
![CleanShot 2023-11-09 at HKkbkrai@2x](https://github.com/poltavchenko/happy-coaching/assets/36765674/d7af0831-07e3-48ae-8e90-4dc60ec437af)

**Comment by poltavchenko** [comment]
1. Looks bad link - fixed in #22 
2. block with margin, not paragraph - fixed in #22 
3. Color not like as design - white text color is bad for WCAG - 
![CleanShot 2023-11-09 at 9aZyryCo](https://github.com/poltavchenko/happy-coaching/assets/8300008/701ccd22-e7db-42c8-a708-56b6692f45fa)
![CleanShot 2023-11-09 at GQYWUCBz](https://github.com/poltavchenko/happy-coaching/assets/8300008/2a19a3cb-b449-4bf2-982b-7699f3098e03)

**Comment by poltavchenko** [comment]
4. Indent from image, looks bad
![CleanShot 2023-11-09 at eSvt5Qiq](https://github.com/poltavchenko/happy-coaching/assets/8300008/154f0fb4-1ba5-4566-b067-c4c81bfe6ea4)
