### ISSUE TITLE
HP. Introduction section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#8]
Introduction section = 3h
Real duration = 40min

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5780&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-09-07 at WJ4AfQYs@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/e807cec8-59f3-46fb-9b68-468b6a8af642)
![CleanShot 2023-09-07 at Q000UlxB@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/c9db1f10-663e-4a29-a099-86f218acbc32)
![CleanShot 2023-09-07 at p5umPVMJ@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/38821d00-03ea-4c13-ba28-9b3469e51a87)
![CleanShot 2023-09-07 at fBDK6CEW@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/7f926ec6-4ef1-4e64-a677-574d3ad718aa)
![CleanShot 2023-09-07 at zPJ6H5nc@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/f2b6bab6-75c8-460e-9d47-37f4adde3873)
![CleanShot 2023-09-07 at DQ2bqWfS@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/d90908b6-c4c2-47f7-8ce3-087c98af11af)
![CleanShot 2023-09-07 at mjbe23zG@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/7de83b4f-6fa3-4e12-8e8a-0ac528b651d5)
![CleanShot 2023-09-07 at G7TLHjDj@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/30078908-40a0-41c6-a81f-95224adee280)
![CleanShot 2023-09-07 at gue3nbhO@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/7a9c3bd7-4629-491d-8d14-4893440ebc13)
![CleanShot 2023-09-07 at jCt2uiS9@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/3ef9fca8-c5e9-4203-a152-d7476e4344e2)
![CleanShot 2023-09-07 at YrIuTSoO@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/660b77e4-800b-4906-99df-c4c0115997fc)
![CleanShot 2023-09-07 at JZgcnrzm@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/fc1b4073-630f-46e8-af5b-406badf5d79a)

Accessibilities
![CleanShot 2023-09-07 at JZgcnrzm@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/92ae0dda-ea06-4a39-a0e5-e5f7954f4c76)

**Comment by poltanka** [comment]
1) Для чего relative 
![CleanShot 2023-11-16 at BikwpBvI](https://github.com/poltavchenko/happy-coaching/assets/36765674/574259f9-3bf9-44a2-b593-c26a4881cfee)
2) rte or prose ? 
![CleanShot 2023-11-16 at RCKtt203](https://github.com/poltavchenko/happy-coaching/assets/36765674/658e762f-d8b8-48c5-971e-46c14a792b79)
