### ISSUE TITLE
HP. Reviews section

### ISSUE THREAD

**Issue by poltavchenko** [poltavchenko/happy-coaching#9]
Reviews section = 3h

Design
https://www.figma.com/file/NWU1Mo4KtRyTrHlaldKbGV/Happy-Coaching-(Copy)?type=design&node-id=508-5832&mode=dev

**Comment by poltavchenko** [comment]
Done

Chrome MacOS
![CleanShot 2023-09-09 at nU6RXziO](https://github.com/poltavchenko/happy-coaching/assets/8300008/a364c60c-4acc-4669-a5b7-0bcc49920ef5)

![CleanShot 2023-09-09 at u5g0xzHb](https://github.com/poltavchenko/happy-coaching/assets/8300008/048e264c-1e3e-4342-9304-031b452a52de)
![CleanShot 2023-09-09 at gSWrMcmN](https://github.com/poltavchenko/happy-coaching/assets/8300008/31bc5cf0-15be-4470-ad1d-cab0f94f6f6f)
![CleanShot 2023-09-09 at nAsCn0kr](https://github.com/poltavchenko/happy-coaching/assets/8300008/18832dc2-9124-4930-8565-3999285a9126)
![CleanShot 2023-09-09 at G3IlfqEA](https://github.com/poltavchenko/happy-coaching/assets/8300008/f6cf5af0-b246-4547-9cef-be78dbc94a4f)
![CleanShot 2023-09-09 at aLaSE9J4](https://github.com/poltavchenko/happy-coaching/assets/8300008/c5ef159c-fff7-47e5-bf99-06f8d1a0667e)

Safari
![CleanShot 2023-09-09 at QhDqGiLU](https://github.com/poltavchenko/happy-coaching/assets/8300008/f8e15084-d593-49f2-a260-2de4c9aecd4b)
![CleanShot 2023-09-09 at LTRLsi7J](https://github.com/poltavchenko/happy-coaching/assets/8300008/26526344-f04b-4134-a839-4cad1d8b260e)

Firefox MacOS
![CleanShot 2023-09-09 at Lyx0Mlcd](https://github.com/poltavchenko/happy-coaching/assets/8300008/43285430-0fd2-479c-b460-0c0aa3b0030f)

iOS + iPadOS
![CleanShot 2023-09-09 at 8G4IUUqE@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/0a06a051-746b-4ae1-93dc-99d08060cc17)
![CleanShot 2023-09-09 at uDbPrPqF@2x](https://github.com/poltavchenko/happy-coaching/assets/8300008/c4f538c4-233a-4338-9748-34525508dce5)

Accessibilities
![CleanShot 2023-09-09 at WYGCVgSb](https://github.com/poltavchenko/happy-coaching/assets/8300008/cc6068b1-d55c-4edc-8e24-0332b175e6cf)

**Comment by poltanka** [comment]
1) Если используешь grid по аналогии с верхней секцией, то тогда еще в div содержимое 
![CleanShot 2023-11-16 at Shykg1YZ](https://github.com/poltavchenko/happy-coaching/assets/36765674/480a3fcc-709f-4cf0-af55-81be597305bd)
2) Если р , то большой отступ 
![CleanShot 2023-11-16 at Ce3tVoZv](https://github.com/poltavchenko/happy-coaching/assets/36765674/5f903ac6-453b-4bdf-a2f7-1bc811b742e5)
3) В дизе ховер белое бг , 
![CleanShot 2023-11-16 at FQQIjT5i](https://github.com/poltavchenko/happy-coaching/assets/36765674/aa56dfac-047e-4c98-a689-f6e7a7677797)
